<?php $this->load->view('templates/header'); ?>
<?php $this->load->view('templates/sidebar'); ?>
<?php $this->load->view('templates/navbar'); ?>
<div class="container">
	<h1 class="text-danger">Welcome to CodeIgniter!</h1>
	<p>This is the default welcome page. You can customize it by editing the view file.</p>
	<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consequatur quod hic dicta sunt vitae, reiciendis ducimus quo. Expedita minus nostrum dignissimos ab praesentium officiis nesciunt voluptatum! Sequi exercitationem id, porro voluptas numquam iusto rem laboriosam doloribus eum minus sapiente asperiores iure, maxime quis sit aspernatur corporis cum ipsum? Quidem ad possimus doloremque facilis sapiente fugiat soluta impedit, atque consequuntur id! Quis cum deserunt voluptates voluptate vel distinctio, consectetur iure non, fuga ab est perspiciatis tenetur pariatur culpa quae iusto fugiat iste, quisquam illum saepe minima. Quisquam hic adipisci quam dolorum consectetur provident est doloribus iste! Quam fuga voluptate numquam cumque?</p>
		<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consequatur quod hic dicta sunt vitae, reiciendis ducimus quo. Expedita minus nostrum dignissimos ab praesentium officiis nesciunt voluptatum! Sequi exercitationem id, porro voluptas numquam iusto rem laboriosam doloribus eum minus sapiente asperiores iure, maxime quis sit aspernatur corporis cum ipsum? Quidem ad possimus doloremque facilis sapiente fugiat soluta impedit, atque consequuntur id! Quis cum deserunt voluptates voluptate vel distinctio, consectetur iure non, fuga ab est perspiciatis tenetur pariatur culpa quae iusto fugiat iste, quisquam illum saepe minima. Quisquam hic adipisci quam dolorum consectetur provident est doloribus iste! Quam fuga voluptate numquam cumque?</p>
		<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consequatur quod hic dicta sunt vitae, reiciendis ducimus quo. Expedita minus nostrum dignissimos ab praesentium officiis nesciunt voluptatum! Sequi exercitationem id, porro voluptas numquam iusto rem laboriosam doloribus eum minus sapiente asperiores iure, maxime quis sit aspernatur corporis cum ipsum? Quidem ad possimus doloremque facilis sapiente fugiat soluta impedit, atque consequuntur id! Quis cum deserunt voluptates voluptate vel distinctio, consectetur iure non, fuga ab est perspiciatis tenetur pariatur culpa quae iusto fugiat iste, quisquam illum saepe minima. Quisquam hic adipisci quam dolorum consectetur provident est doloribus iste! Quam fuga voluptate numquam cumque?</p>
			<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consequatur quod hic dicta sunt vitae, reiciendis ducimus quo. Expedita minus nostrum dignissimos ab praesentium officiis nesciunt voluptatum! Sequi exercitationem id, porro voluptas numquam iusto rem laboriosam doloribus eum minus sapiente asperiores iure, maxime quis sit aspernatur corporis cum ipsum? Quidem ad possimus doloremque facilis sapiente fugiat soluta impedit, atque consequuntur id! Quis cum deserunt voluptates voluptate vel distinctio, consectetur iure non, fuga ab est perspiciatis tenetur pariatur culpa quae iusto fugiat iste, quisquam illum saepe minima. Quisquam hic adipisci quam dolorum consectetur provident est doloribus iste! Quam fuga voluptate numquam cumque?</p>
			<p>lorem1000</p>
</div>


<?php $this->load->view('templates/footer'); ?>
<?php $this->load->view('templates/scripts'); ?>
